### ISSUE TITLE
Source map generated by gulp-sourcemaps is invalid.

### ISSUE THREAD

**Issue by stijnvn** [sindresorhus/gulp-traceur#59] opened 2015-02-02 18:26 UTC
The source maps generated by `gulp-sourcemaps` are invalid. Source maps generated by the `traceur` command do work correctly.

For example trying to step into the constructor on on this [line](https://github.com/stijnvn/gulp-traceur-demo/blob/master/app/bootstrap.js#L12) does not work with the gulp generated source map. If I generate the source map with `traceur --out app.js --source-maps file bootstrap.js` I can step into the constructor.

For some reason, the mappings array remains empty.

**Comment by stijnvn** [comment] 2015-02-02 20:34
Probably the same issue as #58.

Could `gulp-traceur` be changed to automatically pass the sourcemaps option to `traceur` when necessary?

**Comment by sindresorhus** [comment] 2015-02-08 08:39
Passing the `sourceMap` option to Traceur makes it not work in a chain as it doesn't take into account existing source maps. That's why all gulp plugins should support gulp-sourcemaps, and why the solution you linked to is not documented.

This plugin implements source maps support correctly. If there's any issues the issue is with Traceur or gulp-sourcemaps. You should open an issue there instead.

Closing this, but feel free to continue the discussion.

**Closed by sindresorhus** 2015-02-08 08:39 UTC

**Comment by cwalther** [comment] 2015-03-04 10:03
I don’t follow. I’m having the same problem and tried to debug it. In my experience (with traceur 0.0.85), if I do not pass `{sourceMaps: true}` to traceur, then `compiler.getSourceMap` ([index.js:24](https://github.com/sindresorhus/gulp-traceur/blob/52ba69e9b753511a47c47dba028f390616934699/index.js#L24)) returns `undefined`. When I do pass `{sourceMaps: true}`, then it returns a source map which is then properly combined with the incoming one by `applySourceMap(file, sourceMap);` (index.js:31). So that does seem to be the proper solution to me. What am I missing?

**Comment by darrinholst** [comment] 2015-08-28 15:21
I'm seeing the same thing with it _fixed_ by adding `{sourceMaps: true}`
